<a href="https://colab.research.google.com/github/nehalmuthu/Automation-of-Ranking-Resumes/blob/main/indexandrankandeval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/sem9/IRpackagenonsubmitfolder/clean.csv')

In [ ]:
df.head()

   Unnamed: 0  ...                         docName
0           0  ...          BAI10010656-Mahesh.pdf
1           1  ...         BAI10010252-Dheeraj.pdf
2           2  ...           BAI10010469-Vivek.pdf
3           3  ...  BAI10010770-Kosuru_Sampath.pdf
4           4  ...      BAI10010547-Shivakumar.pdf

[5 rows x 5 columns]

In [ ]:
import numpy as np
import pandas as pd

def index(files,bag):
    d=dict()
    for i in range(len(files)):
        for w in bag[i]:
            if w in d:
                d[w].add(files[i])
            else:
                d[w]=set()
                d[w].add(files[i])
    return d    

files=[]
bag=[]                   
files=df['docName']
bag=[x.split() for x in df['text']]

In [ ]:
d=index(files,bag)

In [ ]:
freq=[]
for i in d:
  freq.append([i,len(d[i])])

In [ ]:
freq.sort(key=lambda x:x[1],reverse=True)
freq=freq[0:4000]
f=[freq[i][0] for i in range(len(freq))]
freq=f

In [ ]:

words=list(d.keys())

words.sort()

In [ ]:
words=words[5900:len(words)]
w=[]
for i in range(len(words)):
  if len(words[i])>=3 and words[i] in freq:
    w.append(words[i])
words=w
print(len(words))

3575

In [ ]:
din=dict()
for i in d:
  if i in words:
    din[i]=d[i]

In [ ]:
len(din)

3575

In [ ]:
from collections import Counter

words=list(din.keys())
words.sort()

#files*words matrix
mat=[[0 for i in range(len(din))] for j in range(len(files))]
#weights are tfidf values
for i in range(len(files)):
    tfd=Counter(bag[i])
    #for normalizing tf term
    mxtf=tfd.most_common(1)[0][1]
    for j in range(len(words)):
        if words[j] in bag[i]:
            #normalize tf 
            tf=tfd[words[j]]/mxtf
            #idf -> (tot docs )/(docss in which word is present)
            idf=np.log10(len(files))/len(din[words[j]])
            mat[i][j]=tf*idf
            
            
            
df=pd.DataFrame(mat)

In [ ]:
df.columns=words

In [ ]:
df.head()

   academia  academic  academy  accelerate  ...  zone  ‘16  “best  “the
0       0.0  0.000059      0.0         0.0  ...   0.0  0.0    0.0   0.0
1       0.0  0.000078      0.0         0.0  ...   0.0  0.0    0.0   0.0
2       0.0  0.000714      0.0         0.0  ...   0.0  0.0    0.0   0.0
3       0.0  0.000064      0.0         0.0  ...   0.0  0.0    0.0   0.0
4       0.0  0.000403      0.0         0.0  ...   0.0  0.0    0.0   0.0

[5 rows x 3575 columns]

In [ ]:
len(df)

570

In [ ]:
df.to_csv('matrix.csv',encoding='utf-8')

In [ ]:
import pandas as pd
import sklearn
import scipy
s=pd.read_csv('/content/drive/MyDrive/sem9/IRpackagenonsubmitfolder/matrix.csv',encoding='utf-8')
#s=df.copy()
v=s.values
#Call scipy.spatial.distance.cosine(u, v) to find the cosine distance between vectors u and v.
# Subtract the result from 1 to find cosine similarity.

In [ ]:
s.head()

   academia  academic  academy  accelerate  ...  zone  ‘16  “best  “the
0       0.0  0.000059      0.0         0.0  ...   0.0  0.0    0.0   0.0
1       0.0  0.000078      0.0         0.0  ...   0.0  0.0    0.0   0.0
2       0.0  0.000714      0.0         0.0  ...   0.0  0.0    0.0   0.0
3       0.0  0.000064      0.0         0.0  ...   0.0  0.0    0.0   0.0
4       0.0  0.000403      0.0         0.0  ...   0.0  0.0    0.0   0.0

[5 rows x 3575 columns]

In [ ]:
query='''
We are hiring a Business Analyst to join our project team. You will work alongside other business analysts and report directly to the project manager. Your main tasks will include performing detailed requirements analysis, documenting processes, and performing some user acceptance testing. To succeed in this role you should have a natural analytical way of thinking and be able to explain difficult concepts to non-technical users.

Business Analyst Responsibilities:
Evaluating business processes, anticipating requirements, uncovering areas for improvement, and developing and implementing solutions.
Leading ongoing reviews of business processes and developing optimization strategies.
Staying up-to-date on the latest process and IT advancements to automate and modernize systems.
Conducting meetings and presentations to share ideas and findings.
Performing requirements analysis.
Documenting and communicating the results of your efforts.
Effectively communicating your insights and plans to cross-functional team members and management.
Gathering critical information from meetings with various stakeholders and producing useful reports.
Working closely with clients, technicians, and managerial staff.
Providing leadership, training, coaching, and guidance to junior staff.
Allocating resources and maintaining cost efficiency.
Ensuring solutions meet business needs and requirements.
Performing user acceptance testing.
Managing projects, developing project plans, and monitoring performance.
Updating, implementing and maintaining procedures.
Prioritizing initiatives based on business needs and requirements.
Serving as a liaison between stakeholders and users.
Managing competing resources and priorities.
Monitoring deliverables and ensuring timely completion of projects.
Business Analyst Requirements:
A bachelor’s degree in business or related field or an MBA.
A minimum of 5 years experience in business analysis or a related field.
Exceptional analytical and conceptual thinking skills.
The ability to influence stakeholders and work closely with them to determine acceptable solutions.
Advanced technical skills.
Excellent documentation skills.
Fundamental analytical and conceptual thinking skills.
Experience creating detailed reports and giving presentations.
Competency in Microsoft applications including Word, Excel, and Outlook.
A track record of following through on commitments.
Excellent planning, organizational, and time management skills.
Experience leading and developing top performing teams.
A history of leading and supporting successful projects.
'''

In [ ]:
import pandas as pd
import sklearn
import scipy
s=pd.read_csv('/content/drive/MyDrive/sem9/IRpackagenonsubmitfolder/matrix.csv',encoding='utf-8')
df=pd.read_csv('/content/drive/MyDrive/sem9/IRpackagenonsubmitfolder/clean.csv')

v=s.values
#Call scipy.spatial.distance.cosine(u, v) to find the cosine distance between vectors u and v.
# Subtract the result from 1 to find cosine similarity.
sel=df[df['label']==1]
relevant=sel['id']
cs=[]
for i in range(len(v)):
  cosine_similarity = 1-scipy.spatial.distance.cosine(v[0], v[i])
  cs.append([df['id'][i],cosine_similarity])

cs.sort(key=lambda x:x[1],reverse=True)
cs=[x[0] for x in cs]
ret=(cs[0:64])
relret = set(relevant).intersection(set(ret))
print('precision@R using cosine:',len(relret)/len(relevant))

precision@R using cosine: 0.390625

In [ ]:
!pip install rank_bm25

Collecting rank_bm25
  Downloading https://files.pythonhosted.org/packages/16/5a/23ed3132063a0684ea66fb410260c71c4ffda3b99f8f1c021d1e245401b5/rank_bm25-0.2.1-py3-none-any.whl
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from rank_bm25) (1.18.5)
Installing collected packages: rank-bm25
Successfully installed rank-bm25-0.2.1

In [ ]:
import pandas as pd
import sklearn
import scipy
s=pd.read_csv('/content/drive/MyDrive/sem9/IRpackagenonsubmitfolder/matrix.csv',encoding='utf-8')
df=pd.read_csv('/content/drive/MyDrive/sem9/IRpackagenonsubmitfolder/clean.csv')

In [ ]:
corpus=list(df['text'])

In [ ]:
from rank_bm25 import BM25Okapi


tokenized_corpus = [doc.split(" ") for doc in corpus]

bm25 = BM25Okapi(tokenized_corpus)

In [ ]:

tokenized_query = query.split(" ")

doc_scores = bm25.get_scores(tokenized_query)

In [ ]:

v=s.values
#Call scipy.spatial.distance.cosine(u, v) to find the cosine distance between vectors u and v.
# Subtract the result from 1 to find cosine similarity.
sel=df[df['label']==1]
relevant=sel['id']
ret=bm25.get_top_n(tokenized_query, corpus, n=3)
relret = set(relevant).intersection(set(ret))

print('Precision@R using BM: ',len(relret)/len(relevant))

Precision@R using BM:  0.3125